/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "AdminApiImpl.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    AdminApiImpl::AdminApiImpl(Pistache::Address addr)
        : AdminApi(addr)
        , irods_admin_{}
    {
    }

    void AdminApiImpl::catalog_admin(const Pistache::Http::Header::Collection& headers,
                       const std::string& body,
                       const Pistache::Optional<std::string>& action,
                       const Pistache::Optional<std::string>& target,
                       const Pistache::Optional<std::string>& arg2,
                       const Pistache::Optional<std::string>& arg3,
                       const Pistache::Optional<std::string>& arg4,
                       const Pistache::Optional<std::string>& arg5,
                       const Pistache::Optional<std::string>& arg6,
                       const Pistache::Optional<std::string>& arg7,
                       Pistache::Http::ResponseWriter& response)
    {
        MACRO_IRODS_ADMIN_API_IMPLEMENTATION
    }
} // namespace io::swagger::server::api

