/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* AdminApiImpl.h
*
* 
*/

#ifndef ADMIN_API_IMPL_H_
#define ADMIN_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>

#include "ModelBase.h"

#include <AdminApi.h>

#include <memory>
#include <string>

#include "irods_rest_admin_api_implementation.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    class AdminApiImpl
        : public io::swagger::server::api::AdminApi
    {
    public:
        AdminApiImpl(Pistache::Address addr);

        ~AdminApiImpl() {};

        void catalog_admin(const Pistache::Http::Header::Collection& headers,
                           const std::string& body,
                           const Pistache::Optional<std::string>& action,
                           const Pistache::Optional<std::string>& target,
                           const Pistache::Optional<std::string>& arg2,
                           const Pistache::Optional<std::string>& arg3,
                           const Pistache::Optional<std::string>& arg4,
                           const Pistache::Optional<std::string>& arg5,
                           const Pistache::Optional<std::string>& arg6,
                           const Pistache::Optional<std::string>& arg7,
                           Pistache::Http::ResponseWriter& response) override;

        irods::rest::admin irods_admin_;
    }; // class AdminApiImpl
} // namespace io::swagger::server::api

#endif // ADMIN_API_IMPL_H_

