/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "AuthApiImpl.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    AuthApiImpl::AuthApiImpl(Pistache::Address addr)
        : AuthApi(addr)
        , irods_auth_{}
    {
    }

    void AuthApiImpl::handler_impl(const Pistache::Http::Header::Collection& headers,
                                   Pistache::Http::ResponseWriter &response)
    {
        MACRO_IRODS_AUTH_API_IMPLEMENTATION
    }
} // namespace io::swagger::server::api

