/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* AuthApiImpl.h
*
* 
*/

#ifndef AUTH_API_IMPL_H_
#define AUTH_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>
#include <memory>
#include "ModelBase.h"

#include <AuthApi.h>

#include <string>

#include "irods_rest_auth_api_implementation.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class AuthApiImpl : public io::swagger::server::api::AuthApi {
public:
    AuthApiImpl(Pistache::Address addr);
    ~AuthApiImpl() { };

    void obtain_token(const Pistache::Http::Header::Collection& headers, const std::string body, const Pistache::Optional<std::string> &user_name, const Pistache::Optional<std::string> &password, const Pistache::Optional<std::string> &auth_type, Pistache::Http::ResponseWriter &response);
    irods::rest::auth irods_auth_;
};

}
}
}
}



#endif
