/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "ListApiImpl.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    ListApiImpl::ListApiImpl(Pistache::Address addr)
        : ListApi(addr)
        , irods_list_{}
    {
    }

    void ListApiImpl::handler_impl(const Pistache::Http::Header::Collection& headers,
                                   const std::string& body,
                                   const Pistache::Optional<std::string>& path,
                                   const Pistache::Optional<std::string>& stat,
                                   const Pistache::Optional<std::string>& permissions,
                                   const Pistache::Optional<std::string>& metadata,
                                   const Pistache::Optional<std::string>& offset,
                                   const Pistache::Optional<std::string>& limit,
                                   Pistache::Http::ResponseWriter& response)
    {
        MACRO_IRODS_LIST_API_IMPLEMENTATION
    }
} // namespace io::swagger::server::api

