/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* ListApiImpl.h
*
* 
*/

#ifndef LIST_API_IMPL_H_
#define LIST_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>
#include <memory>
#include "ModelBase.h"

#include <ListApi.h>

#include <string>

#include "irods_rest_list_api_implementation.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class ListApiImpl : public io::swagger::server::api::ListApi {
public:
    ListApiImpl(Pistache::Address addr);
    ~ListApiImpl() { };

    void stream(const Pistache::Http::Header::Collection& headers, const std::string body, const Pistache::Optional<std::string> &path, const Pistache::Optional<std::string> &stat, const Pistache::Optional<std::string> &permissions, const Pistache::Optional<std::string> &metadata, const Pistache::Optional<std::string> &offset, const Pistache::Optional<std::string> &limit, Pistache::Http::ResponseWriter &response);
    irods::rest::list irods_list_;
};

}
}
}
}



#endif
