/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "StreamGetApiImpl.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    StreamGetApiImpl::StreamGetApiImpl(Pistache::Address addr)
        : StreamGetApi(addr)
        , irods_stream_get_{}
    {
    }

    void StreamGetApiImpl::handler_impl(const Pistache::Http::Header::Collection& headers,
                                        const std::string& body,
                                        const std::string& path,
                                        const std::string& count,
                                        const Pistache::Optional<std::string>& offset,
                                        Pistache::Http::ResponseWriter& response)
    {
        MACRO_IRODS_STREAM_GET_API_IMPLEMENTATION
    }
} // namespace io::swagger::server::api

