/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* TicketApiImpl.h
*
* 
*/

#ifndef TICKET_API_IMPL_H_
#define TICKET_API_IMPL_H_

#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>

#include "ModelBase.h"

#include <TicketApi.h>

#include <memory>
#include <string>

#include "irods_rest_ticket_implementation.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    class TicketApiImpl
        : public io::swagger::server::api::TicketApi
    {
    public:
        TicketApiImpl(Pistache::Address addr);

        ~TicketApiImpl() = default;

        void handler_impl(const Pistache::Rest::Request& request,
                          Pistache::Http::ResponseWriter& response) override;

        irods::rest::ticket irods_ticket_;
    }; // class TicketApiImpl
} // namespace io::swagger::server::api

#endif // TICKET_API_IMPL_H_

