/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "ZoneReportApiImpl.h"

namespace io::swagger::server::api
{
    using namespace io::swagger::server::model;

    ZoneReportApiImpl::ZoneReportApiImpl(Pistache::Address addr)
        : ZoneReportApi(addr)
        , irods_zone_report_{}
    {
    }

    void ZoneReportApiImpl::handler_impl(const Pistache::Rest::Request& request,
                                         Pistache::Http::ResponseWriter& response)
    {
        auto [code, msg] = irods_zone_report_(request, response);
        response.send(code, msg);
    }
} // namespace io::swagger::server::api

