/**
* iRODS Query API
* This is the iRODS Query API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

/*
* QueryApiImpl.h
*
* 
*/

#ifndef QUERY_API_IMPL_H_
#define QUERY_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <pistache/optional.h>
#include <memory>

#include <QueryApi.h>

#include "Query_results.h"
#include <string>

#include "connection_pool.hpp"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

class QueryApiImpl : public io::swagger::server::api::QueryApi {
public:
    QueryApiImpl(Pistache::Address addr);
    ~QueryApiImpl() { };
void catalog_query(
        const Pistache::Optional<std::string> &queryString,
        const Pistache::Optional<std::string> &queryLimit,
        const Pistache::Optional<std::string> &rowOffset,
        const Pistache::Optional<std::string> &queryType,
        Pistache::Http::ResponseWriter &response);
std::shared_ptr<irods::connection_pool> connection_pool_;
};

}
}
}
}



#endif
