version: '3'

services:
    nginx-reverse-proxy:
        build:
            context: ../runner
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"

    irods-client-rest-cpp:
        build:
            context: .
            dockerfile: irods_client_rest_cpp.Dockerfile
        volumes:
            - ./irods-client-rest-cpp_0.9.3-0~focal_amd64.deb:/irods-client-rest-cpp_package.deb:ro
        environment:
            - local_package=/irods-client-rest-cpp_package.deb
