#!/bin/sh
#
# See "man chkconfig" for information on next two lines (RedHatCompatible Only)
# chkconfig: 2345 90 10
# description: iRODS
#
#
# Following lines are in conformance with LSB 1.2 spec
### BEGIN INIT INFO
# Provides:          irods_client_rest_cpp
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Manages the iRODS C++ REST service
# Description:       Manages the iRODS C++ REST service
### END INIT INFO

find_os() {
    UNAMERESULTS=`uname`
    if [ -f "/etc/redhat-release" ]; then       # CentOS and RHEL and Fedora
        DETECTEDOS="RedHatCompatible"
    elif [ -f "/etc/SuSE-release" ]; then       # SuSE
        DETECTEDOS="SuSE"
    elif [ -f "/etc/arch-release" ]; then       # ArchLinux
        DETECTEDOS="ArchLinux"
    elif [ -f "/etc/lsb-release" ]; then        # Ubuntu
        DETECTEDOS="Ubuntu"
    elif [ -f "/etc/debian_version" ]; then     # Debian
        DETECTEDOS="Debian"
    elif [ -f "/usr/bin/sw_vers" ]; then        # MacOSX
        DETECTEDOS="MacOSX"
    elif [ "$UNAMERESULTS" == "SunOS" ]; then   # Solaris
        DETECTEDOS="Solaris"
    fi

    echo "$DETECTEDOS"
}

set -e

PROJECT="irods_client_rest_cpp"
PREFIX="${PROJECT}_"

DETECTEDOS=find_os

stop_irods_client_rest_cpp() {
    for PID in `ps -ef | grep $PREFIX | grep -v 'grep' |  awk '{print $2}'`
    do
        kill -9 ${PID}
    done
}

start_irods_client_rest_cpp() {
    for API in `ls /usr/sbin/$PREFIX*`
    do
        ${API}&
    done
}

if [ "$DETECTEDOS" = "MacOSX" ] ; then
    SU_SHELL_OPTS="-l"
else
    SU_SHELL_OPTS="--shell=/bin/bash --login"
fi

case $1 in
status)
    ps -ef | grep $PREFIX | grep -v "grep"
    ;;
start)
    start_irods_client_rest_cpp
    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] ; then
        touch /var/lock/subsys/${PROJECT}
    fi
    ;;
stop)
    stop_irods_client_rest_cpp
    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] ; then
        touch /var/lock/subsys/${PROJECT}
    fi
    ;;
restart)
    stop_irods_client_rest_cpp
    start_irods_client_rest_cpp
    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] ; then
        touch /var/lock/subsys/${PROJECT}
    fi
    ;;
force-reload)
    stop_irods_client_rest_cpp
    start_irods_client_rest_cpp
    if [ "$DETECTEDOS" = "RedHatCompatible" -o "$DETECTEDOS" = "SuSE" ] ; then
        touch /var/lock/subsys/${PROJECT}
    fi
    ;;
*)
    echo "/etc/init.d/${PROJECT} :: [$1] is not supported." 1>&2
    echo "Usage: /etc/init.d/${PROJECT} {start|stop|status|restart|force-reload}" 1>&2
    exit 1
esac
