version: '3'

services:
    nginx-reverse-proxy:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        ports:
            - "80:80"

    irods-client-rest-cpp:
        build:
            context: .
            dockerfile: irods_client_rest_cpp.Dockerfile
            args:
                - local_package=irods-client-rest-cpp_0.9.3-0~focal_amd64.deb
        volumes:
            - ./irods_client_rest_cpp.json:/etc/irods_client_rest_cpp/irods_client_rest_cpp.json:ro
