/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "AuthApi.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

AuthApi::AuthApi(Pistache::Address addr)
    : httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(addr))
{ };

void AuthApi::init(size_t thr = 2) {
    auto opts = Pistache::Http::Endpoint::options()
        .threads(thr);
    httpEndpoint->init(opts);
    setupRoutes();
}

void AuthApi::start() {
    httpEndpoint->setHandler(router.handler());
    httpEndpoint->serve();
}

void AuthApi::shutdown() {
    httpEndpoint->shutdown();
}

void AuthApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Post(router, base + "/auth", Routes::bind(&AuthApi::obtain_token_handler, this));

    // Default handler, called when a route is not found
    router.addCustomHandler(Routes::bind(&AuthApi::auth_api_default_handler, this));
}

void AuthApi::obtain_token_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto userName = request.query().get("userName");
    auto password = request.query().get("password");
    auto authType = request.query().get("authType");
    
    try {
      this->obtain_token(request.headers(), request.body(), userName, password, authType, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void AuthApi::auth_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

