/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "StreamGetApi.h"

#include "spdlog/spdlog.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

StreamGetApi::StreamGetApi(Pistache::Address addr)
    : httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(addr))
{ };

void StreamGetApi::init(size_t thr = 2) {
    auto opts = Pistache::Http::Endpoint::options()
        .threads(thr);
    httpEndpoint->init(opts);
    setupRoutes();
}

void StreamGetApi::start() {
    httpEndpoint->setHandler(router.handler());
    httpEndpoint->serve();
}

void StreamGetApi::shutdown() {
    httpEndpoint->shutdown();
}

void StreamGetApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(router, base + "/stream", Routes::bind(&StreamGetApi::handler, this));

    // Default handler, called when a route is not found
    router.addCustomHandler(Routes::bind(&StreamGetApi::default_handler, this));
}

void StreamGetApi::handler(const Pistache::Rest::Request& request,
                           Pistache::Http::ResponseWriter response)
{
    try {
        spdlog::info("Incoming request from [{}].", request.address().host());

        // Getting the query params
        auto path = request.query().get("path");
        auto offset = request.query().get("offset");
        auto count = request.query().get("count");

        this->stream(request.headers(), request.body(), path.get(), count.get(), offset, response);
    }
    catch (const std::runtime_error& e) {
        //send a 400 error
        response.send(Pistache::Http::Code::Bad_Request, e.what());
        return;
    }
}

void StreamGetApi::default_handler(const Pistache::Rest::Request& request,
                                   Pistache::Http::ResponseWriter response)
{
    response.send(Pistache::Http::Code::Not_Found, "The requested StreamGet method does not exist");
}

}
}
}
}

