/**
* iRODS REST API
* This is the iRODS REST API
*
* OpenAPI spec version: 1.0.0
* Contact: info@irods.org
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/

#include "StreamPutApi.h"

#include "constants.hpp"

#include "spdlog/spdlog.h"

namespace io {
namespace swagger {
namespace server {
namespace api {

using namespace io::swagger::server::model;

StreamPutApi::StreamPutApi(Pistache::Address addr)
    : httpEndpoint(std::make_shared<Pistache::Http::Endpoint>(addr))
{ };

void StreamPutApi::init(size_t thr = 2) {
    auto opts = Pistache::Http::Endpoint::options()
        .threads(thr);
    httpEndpoint->init(opts);
    setupRoutes();
}

void StreamPutApi::start() {
    httpEndpoint->setHandler(router.handler());
    httpEndpoint->serve();
}

void StreamPutApi::shutdown() {
    httpEndpoint->shutdown();
}

void StreamPutApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Put(router, irods::rest::base_url + "/stream", Routes::bind(&StreamPutApi::handler, this));

    // Default handler, called when a route is not found
    router.addCustomHandler(Routes::bind(&StreamPutApi::default_handler, this));
}

void StreamPutApi::handler(const Pistache::Rest::Request& request,
                           Pistache::Http::ResponseWriter response)
{
    try {
        this->handler_impl(request, response);
    }
    catch (const std::runtime_error& e) {
        response.send(Pistache::Http::Code::Bad_Request, e.what());
    }
}

void StreamPutApi::default_handler(const Pistache::Rest::Request& request,
                                   Pistache::Http::ResponseWriter response)
{
    response.send(Pistache::Http::Code::Not_Found, "The requested StreamPut method does not exist");
}

}
}
}
}

